#端口号
server:
  port: 8081
#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.141.254:63316/Cpottery?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: pottery
    password: yanjqpottery123

  mvc:
      view:
           prefix: "/WEB-INF/pages/"
  servlet:
       multipart:
         max-file-size: 100MB
         max-request-size: 100MB
  http:
      encoding:
      charset: UTF-8
      force: true
      enabled: true

  resources:
    static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.impi.domain

